### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by nc0fr** [nc0fr/bloow#5]
Continuous Integration is a good practice from the Ops world that helps maintaining a certain level of quality in software. It also automates some tedious processes: applying a style guide, running tests, &c.

GitHub Actions and similar solutions offers free CI (at a reasonable limit) for open-source project. This issue services as a place to discuss over which service to use and what to execute within runners.

**Tasks:**

- [ ] Applying style guide
- [ ] Building up-to-date documentation from code (`jsdoc`)
- [ ] Ticket triage
- [ ] Preview environment
- [ ] One-click deployment
- [ ] Artifacts uploading
- [ ] Release creations
- [x] cool

**Services:**

- [GitHub Actions](https://github.com/features/actions): limited in functionalities and pretty annoying, but well integrated with GitHub and easy to understand in general. Risks of vendor locking
- [CircleCI](https://circleci.com/): works well, but not familiar.
- Other?
- *I don't plan on self-hosting CI, just exploit some companies free plan*
